version: '3.8'

services:
  app:
    image: laravelfans/laravel
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bash -c "cd /var/www/html && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
